name: my_daily_exercise
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  riverpod_annotation:
  freezed_annotation: ^2.4.1
  go_router: ^14.1.4
  image_picker: ^1.1.2
  json_annotation: ^4.9.0
  realm: ^3.0.0
  background_hiit_timer: ^1.0.0-dev.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.10
  freezed: ^2.5.2
  json_serializable: ^6.8.0

  # the code generator
  riverpod_generator:
  # riverpod_lint makes it easier to work with Riverpod
  riverpod_lint:
  # import custom_lint too as riverpod_lint depends on it
  custom_lint:

flutter:
  uses-material-design: true
